# Generated by Django 4.2.2 on 2023-12-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eventdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                ("event_location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Candidatedirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_column="event",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="candidate_app.eventdetails",
                    ),
                ),
            ],
        ),
    ]
